### ISSUE TITLE
USER STORY: Add products to Cart

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#12]
As a **Site User**  I can **add products to my shopping cart** so that **I can conveniently purchase multiple items at once**

## Acceptance Criteria:
* When I open a product details card I should see an "Add to Cart" button next to the product.:
* When I click "Add to Cart" the product should be added to my shopping cart and I should see a success message.:
* When I navigate to the "My Cart" page I should be able to view the list of products I have added:

## Tasks:
  - [x] Design and implement the template for the product card, including an "Add to Cart" button.
  - [x] Implement the logic to add products to the user's shopping cart when they click "Add to Cart."
  - [x] Implement messages to provide feedback to the user when an item is added to cart.
  - [x] Design and implement the template for the "My Cart" page.
  - [x] Implement the logic to display the user's shopping cart on the "My Cart" page.
