### ISSUE TITLE
USER STORY: Update Cart

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#14]
As a **Site User**  I can **adjust the quantity of products in my shopping** so that **I can control the quantity for each item I want to purchase**

## Acceptance Criteria:
* When I navigate to the "My Cart" page or section I should be able to view the list of products I have added along with the ability to increase or decrease the quantity for each product.:
* When I increase or decrease the quantity of a product the total cart price should update accordingly based on the adjusted quantities:

## Tasks:
  - [x] Design and implement the template for the "My Cart" page, including quantity adjustment options for each product.
  - [x] Implement the logic for the quantity adjustment feature.
  - [x] Design and implement the buttons for increasing and decreasing quantities.
  - [x] Implement the logic to update the cart total price when product quantities are adjusted.
