### ISSUE TITLE
USER STORY: Apply discount codes

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#15]
As a **Site User**  I can **apply discount codes to my order** so that **I can receive savings and discounts on my purchases**

## Acceptance Criteria:
* When I navigate to the bag page or section I should see a field where I can enter a discount code.:
* When I enter a valid discount code in the field and apply it, the bag total should be updated to reflect the discount, and the discount amount should be displayed.
* If the discount code is invalid I should receive an error message:

## Tasks:
  - [x] Create a database model for discount codes
  - [x] Design and implement the template for the bag page,to include a field for entering discount codes.
  - [x] Implement the logic to display the user's shopping cart on the bag page, including the discount code field.
  - [x]  Implement the logic to validate and apply discount codes to the bag total.
  - [x] Implement the logic to update the final total order price with the applied discount during the checkout process.
  - [x] Implement error handling for invalid or expired discount codes, displaying relevant error messages.
