### ISSUE TITLE
USER STORY: Delete a Product

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#19]
As a **Superuser/Administrator**  I can **delete existing products on the website** so that **so that I can update and manage the product catalogue**

## Acceptance Criteria:
* As a logged in Superuser/Administrator I have access to an "Delete" button for each product listing :
* When I select delete on a product from the list of available products the selected product should be removed from the product catalog
* When I complete the delete process I should see a confirmation message indicating that the product has been successfully deleted:
* When I navigate to the product listing page I should verify the product is no longer listed:

## Tasks:
  - [x] Design and implement the "Delete Product" page.
  - [x] Implement the logic to pre-fill a form with the existing product information.
  - [x]  Implement the logic to delete the selected product.
  - [x]  Implement a confirmation message or notification upon successful deletion of the product.
