### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#2]
As a **Site User**  I can **navigate through the website** so that ** I can easily access all pages of the website**

## Acceptance Criteria:
* The navigation bar is displated at the top of the webpage:
* When I click on a link I am promptly redirected to the corresponding page.:

## Tasks:
  - [x] Design the navigation bar
  - [x] Ensure the navigation bar is fully responsive
  - [x] Ensure all links in the navigation bar redirect to the correct page.
