### ISSUE TITLE
USER STORY: Sort Products by price, date and alphabetically

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#20]
As a **Site User**  I can **easily sort products by price, date and alphabetically** so that **I can find products that interest me**

## Acceptance Criteria:

* When I navigate to a product sort dropdown menu I should see a list of available sorting options to choose from
* When I select a specific sorting option from the list, the list of displayed products should be sorted by the selected option.

## Tasks:
  - [x]  Create a sorting dropdown menu on the home page and all products page.
  - [x]  Add options for sorting by price, date and alphabetically in the dropdown.
  - [x] Create the logic to handle sorting products by name and price.
  - [x]  Implement sorting based on the user's selected sorting option.
