### ISSUE TITLE
USER STORY: Checkout

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#21]
As a **Site User**  I can **complete the checkout step** so that **I can purchase the products added to my bag**

## Acceptance Criteria:
* When I review my cart contents I should see a summary of items in my cart, including their names, quantities, prices, and total cost.
* When I go to fill out my delivery and billing information I should see fields for full name, email, phone number and shipping address.
* If my order total meets or exceeds the free delivery threshold then it should be displayed as €0.

## Tasks:
  - [x]  Create checkout app and order models.
  - [x]  Create a checkout template that displays the bag contents
  - [x] Design and  Implement a form to collect and validate user's billing and delivery information
  - [x] Implement the logic to determine the delivery cost based on the amount spent and the order total.
