### ISSUE TITLE
USER STORY: Newsletter signup form

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#24]
As a **Site User**  I can **sign up for newsletters on the website** so that **I can keep update with the latest news and offers**

## Acceptance Criteria:
* When I visit the site I should see a form for signing up to the newsletter:
* When I subscribe to the news letter I should see a confirmation message:

## Tasks:
  - [x] Create a Mailchimp account
  - [x] Add the mailchimp code to the footer
  - [x] Apply custom styling
  - [x] Test that the from works correctly
