### ISSUE TITLE
USER STORY: Robots.txt and Sitemap.xml

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#28]
As a **site developer**  I can **create a Robots.txt and Sitemap.xml file** so that **I improve my SEO**

## Acceptance Criteria:
* Project has Robots.txt and Sitemap.xml in root directory :

## Tasks: 
  - [x] Go to https://www.xml-sitemaps.com/  and enter deployed website url.
  - [x] Click start and wait for file to be generated, download file to PC.
  - [x] Create robots.txt file in root directory.
  - [x] Add user-agent text, and disallow directories
