### ISSUE TITLE
USER STORY: Create external database and setup hosting for static and media files

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#29]
As a **site developer**  I can **connect external database storage and hosting services** so that **the site data is stored successfully**

## Acceptance Criteria:
* Site data is stored in Elephant SQL database:
* Static and media files are stored in Amazon Web Services:

## Tasks:
  - [x] Configure setting for Elephant SQL
  - [x] Configure settings for static files
  - [x] Configure Amazon Web Services settings
  - [x] Configure Django's settings to connect to AWS.
  - [x] Run migrations
  - [x] Test database and media storage
