### ISSUE TITLE
USER STORY: View all products

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#3]
As a **Site User**  I can **view a list of all products** so that **so that I can choose products to purchase**

## Acceptance Criteria:
* When I click on the "View all" link in the navigation menu I should be redirected to a page displaying a paginated list of all products.:
* Each products should be displayed in a card:

## Tasks:
  - [x] Create a Django model, view and template for displaying all products
  - [x] Implement pagination for the list of products
  - [x] Create a "All Products" link in the products menu
