### ISSUE TITLE
USER STORY: Favourites

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#30]
As a **Site User**  I can **select products to add to my favourites list** so that **I can easily find them in future**

## Acceptance Criteria:
* As a logged in user I can click on product to add to my favourites list:

## Tasks:
  - [x] Create favourties model 
  - [x] Create view
  - [x] Create favourites page
  - [x] Add favourites link to header
