### ISSUE TITLE
USER STORY: Search products

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#6]
As a **Site User**  I can **search for products in the shop by entering keyword** so that **I can quickly find products that are of interest to me**

## Acceptance Criteria:
* When I enter keywords or phrases into a search input field and click the "Search" button, I should be directed to a search results page displaying a list of products that match the search query.:
* When I click on a product from the search results, I should be directed to the "Single Product View" page for that book:
* When I enter a search query that yields no results, I should see a message indicating that there are no products matching the search query:

## Tasks:
  - [x] Create a Django view and template for handling product searches 
  - [x] Write a view function that retrieves and displays products matching the search query
  - [x] Implement message where search returns no results
