### ISSUE TITLE
USER STORY: Create Account

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#7]
As a **Site User**  I can **register for an account** so that **so that I can have access to all functionality**

## Acceptance Criteria:
* I should see a "Create Account" button on the navigation menu.:
* I click on the "Create Account" I am redirected to the create account page, I should see a form with fields to enter my name, email address, and password.:
* When I fill in the Create Account form with valid information, I can submit the form, and I should be redirected to a "Account Created Successful" page:

## Tasks:
  - [x] Design and implement the template for the navigation menu, including a "Create Account" button.
  - [x]  Install and configure django-allauth
  - [x] Create a form template provided by django-allauth for user account registration.
  - [x] Configure email confirmation and account activation settings provided by django-allauth.
  - [x] Design and implement the frontend template for the "Registration Successful" page or notification.
