### ISSUE TITLE
USER STORY: User Login

### ISSUE THREAD

**Issue by eric-blake** [eric-blake/wine-store#8]
As a **Site User**  I can **log in to my account** so that **view my account details and make purchases**

## Acceptance Criteria:
* When I visit the website I should see a "Log In" button on the navigation menu.:
* When I click on the "Log In" button I am redirected to the login page. I should see a form with fields to enter my username password.:
* When I submit the login form I should be successfully logged in to my account. 
* If I enter invalid login credentials, I should receive an appropriate error message indicating that the login attempt was unsuccessful.

## Tasks:
  - [x] Design and implement the template for the navigation menu, including a "Log In" button.
  - [x] Create a login form template for user authentication.
  - [x] Design and implement the "Login Successful" notification message.
  - [x] Test the login process to verify that users can successfully log in with valid credentials.
  - [x] Test the login process to verify that users can not log in with invalid credentials.
